### PR TITLE
Add Guix R Us installation instructions

### PR DESCRIPTION
**Pull request by jgarte**

### CODE REVIEW

**Comment by mohkale** [comment]
Thanks for this. I'll wait until you've confirmed the package can be installed and works out of the box with guix before merging. See also #1.

**Comment by jgarte** [comment]
Hi @mohkale 

Here's a screenshot of me editing my config with spaceleader (iinstalled with guix).

2022-06-03-140547_1600x900_scrot

It's working for me. 

Thanks for this great package.

**Comment by jgarte** [comment]
I also sent spaceleader to upstream GNU Guix for inclusion in their package collection:

https://issues.guix.gnu.org/55786

We'll have to wait for peer review for them to include it.

**Comment by mohkale** [comment]
LGTM then, thanks for contributing :-).

**Pull request merged**
